/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682838165/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/mnt/shared-scratch/Rajendran_J/matthewdelorenzo/miniconda3/envs/rltf=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

module top_module(x, f);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  output f;
  wire f;
  input [4:1] x;
  wire [4:1] x;
  INV_X2 _09_ (
    .A(x[4]),
    .ZN(_05_)
  );
  INV_X1 _10_ (
    .A(x[2]),
    .ZN(_06_)
  );
  NAND2_X2 _11_ (
    .A1(_05_),
    .A2(_06_),
    .ZN(_07_)
  );
  NAND2_X1 _12_ (
    .A1(x[4]),
    .A2(x[2]),
    .ZN(_08_)
  );
  NAND2_X2 _13_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_00_)
  );
  NAND2_X2 _14_ (
    .A1(_05_),
    .A2(x[1]),
    .ZN(_01_)
  );
  INV_X1 _15_ (
    .A(x[3]),
    .ZN(_02_)
  );
  NAND2_X2 _16_ (
    .A1(_01_),
    .A2(_02_),
    .ZN(_03_)
  );
  NAND2_X2 _17_ (
    .A1(_00_),
    .A2(_03_),
    .ZN(_04_)
  );
  INV_X2 _18_ (
    .A(_04_),
    .ZN(f)
  );
endmodule
