/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682838165/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/mnt/shared-scratch/Rajendran_J/matthewdelorenzo/miniconda3/envs/rltf=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

module top_module(in, parity);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  input [7:0] in;
  wire [7:0] in;
  output parity;
  wire parity;
  INV_X1 _34_ (
    .A(in[7]),
    .ZN(_02_)
  );
  NAND2_X1 _35_ (
    .A1(_02_),
    .A2(in[6]),
    .ZN(_03_)
  );
  NAND2_X2 _36_ (
    .A1(_01_),
    .A2(_03_),
    .ZN(_04_)
  );
  INV_X1 _37_ (
    .A(in[4]),
    .ZN(_05_)
  );
  NAND2_X1 _38_ (
    .A1(_05_),
    .A2(in[5]),
    .ZN(_06_)
  );
  INV_X1 _39_ (
    .A(in[5]),
    .ZN(_07_)
  );
  NAND2_X1 _40_ (
    .A1(_07_),
    .A2(in[4]),
    .ZN(_08_)
  );
  NAND2_X2 _41_ (
    .A1(_06_),
    .A2(_08_),
    .ZN(_09_)
  );
  XNOR2_X1 _42_ (
    .A(_04_),
    .B(_09_),
    .ZN(_10_)
  );
  INV_X1 _43_ (
    .A(in[3]),
    .ZN(_11_)
  );
  INV_X1 _44_ (
    .A(in[2]),
    .ZN(_12_)
  );
  NAND2_X1 _45_ (
    .A1(_11_),
    .A2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _46_ (
    .A1(in[3]),
    .A2(in[2]),
    .ZN(_14_)
  );
  NAND2_X2 _47_ (
    .A1(_13_),
    .A2(_14_),
    .ZN(_15_)
  );
  INV_X1 _48_ (
    .A(in[0]),
    .ZN(_16_)
  );
  NAND2_X1 _49_ (
    .A1(_16_),
    .A2(in[1]),
    .ZN(_17_)
  );
  INV_X1 _50_ (
    .A(in[1]),
    .ZN(_18_)
  );
  NAND2_X1 _51_ (
    .A1(_18_),
    .A2(in[0]),
    .ZN(_19_)
  );
  NAND2_X2 _52_ (
    .A1(_17_),
    .A2(_19_),
    .ZN(_20_)
  );
  XNOR2_X1 _53_ (
    .A(_15_),
    .B(_20_),
    .ZN(_21_)
  );
  NAND2_X1 _54_ (
    .A1(_10_),
    .A2(_21_),
    .ZN(_22_)
  );
  INV_X1 _55_ (
    .A(_04_),
    .ZN(_23_)
  );
  NAND2_X1 _56_ (
    .A1(_23_),
    .A2(_09_),
    .ZN(_24_)
  );
  INV_X1 _57_ (
    .A(_09_),
    .ZN(_25_)
  );
  NAND2_X1 _58_ (
    .A1(_25_),
    .A2(_04_),
    .ZN(_26_)
  );
  NAND2_X1 _59_ (
    .A1(_24_),
    .A2(_26_),
    .ZN(_27_)
  );
  INV_X1 _60_ (
    .A(_15_),
    .ZN(_28_)
  );
  NAND2_X1 _61_ (
    .A1(_28_),
    .A2(_20_),
    .ZN(_29_)
  );
  INV_X1 _62_ (
    .A(_20_),
    .ZN(_30_)
  );
  NAND2_X1 _63_ (
    .A1(_30_),
    .A2(_15_),
    .ZN(_31_)
  );
  NAND2_X1 _64_ (
    .A1(_29_),
    .A2(_31_),
    .ZN(_32_)
  );
  NAND2_X1 _65_ (
    .A1(_27_),
    .A2(_32_),
    .ZN(_33_)
  );
  NAND2_X1 _66_ (
    .A1(_22_),
    .A2(_33_),
    .ZN(parity)
  );
  INV_X1 _67_ (
    .A(in[6]),
    .ZN(_00_)
  );
  NAND2_X1 _68_ (
    .A1(_00_),
    .A2(in[7]),
    .ZN(_01_)
  );
endmodule
