/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682838165/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/mnt/shared-scratch/Rajendran_J/matthewdelorenzo/miniconda3/envs/rltf=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

module top_module(x, f);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  output f;
  wire f;
  input [4:1] x;
  wire [4:1] x;
  INV_X1 _05_ (
    .A(x[4]),
    .ZN(_01_)
  );
  INV_X1 _06_ (
    .A(x[3]),
    .ZN(_02_)
  );
  NAND3_X1 _07_ (
    .A1(_01_),
    .A2(_02_),
    .A3(x[2]),
    .ZN(_03_)
  );
  NAND2_X1 _08_ (
    .A1(x[1]),
    .A2(x[4]),
    .ZN(_04_)
  );
  NAND2_X1 _09_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_00_)
  );
  INV_X1 _10_ (
    .A(_00_),
    .ZN(f)
  );
endmodule
